version: '4.14.1'

services:
  #MongoDB Services
  mongo_db:
    container_name : db_container
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongo_db:/data/db


  #NodeJS Services
  api:
    build: .
    ports:
      - "4000:5000"
    environment:
      - PORT:5000
      - MONGO_DB_URL:mongodb://mongo_db:27017
      - ACCESS_TOKEN_SECRET:TUtreW42OEA2N20
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}